const fs = require('fs');

const TEMPLATES = {
  "3D ANIMATOR": {
    "1": "Hari ini {nama} belajar mengenal perangkat komputer beserta fungsi komponen-komponennya. {nama} juga diajarkan kebiasaan baik dalam merawat dan menjaga gadget agar tetap aman dan tidak mudah rusak.",
    "2": "Hari ini {nama} berlatih mengetik di komputer untuk melatih ketangkasan dan koordinasi motorik. Selain itu, {nama} juga memahami pentingnya *media balance* (keseimbangan waktu penggunaan gadget).",
    "3": "Hari ini {nama} mulai mengenal konsep dasar coding sebagai bahasa instruksi komputer. {nama} juga diajak memahami pentingnya mengurangi *screen time* demi kesehatan mata dan tubuh.",
    "4": "Hari ini {nama} berkenalan dengan dunia robotika dan belajar memberikan instruksi coding sederhana untuk menggerakkan robot secara terarah.",
    "5": "Hari ini {nama} belajar konsep *Event* dalam coding (memicu aksi saat ada perintah tertentu). {nama} mempraktikkannya secara langsung untuk mengendalikan pergerakan robot.",
    "6": "Hari ini {nama} belajar konsep *Loop* (perulangan perintah otomatis). Melalui tantangan interaktif bersama karakter Scrat, {nama} berhasil membuat gerakan berulang yang rapi dan efisien.",
    "7": "Hari ini {nama} mulai mengenal aplikasi ScratchJr dan belajar membuat animasi kreatif pertamanya menggunakan balok-balok kode visual yang menyenangkan.",
    "8": "Hari ini {nama} mengikuti sesi Review & Coding Challenge 1 untuk mempraktikkan materi Lesson 1–7. {nama} berhasil menyelesaikan tantangan dengan baik dan menunjukkan antusiasme yang tinggi!",
    "9": "Hari ini {nama} belajar menggunakan fitur Grid Mode di ScratchJr untuk menentukan posisi karakter secara presisi, lalu berhasil membuat proyek animasi roket terbang menuju bulan.",
    "10": "Hari ini {nama} belajar menggunakan fitur *Send Message* di ScratchJr untuk menghubungkan aksi antar karakter, lalu membuat game animasi balapan hewan (Animal Race).",
    "11": "Hari ini {nama} belajar mengenal internet beserta manfaat positifnya. {nama} juga belajar konsep *Debugging* (mencari dan memperbaiki kesalahan kode secara mandiri).",
    "12": "Hari ini {nama} belajar mengenali berbagai bentuk geometri (shapes) sambil coding interaktif, serta memahami panduan penting mengenai hal-hal yang aman dan tidak aman dibagikan di internet.",
    "13": "Hari ini {nama} mengingat kembali fungsi tombol-tombol pada robot dan berhasil memprogram robot untuk bergerak membentuk berbagai pola bangun ruang.",
    "14": "Hari ini {nama} semakin mahir membuat animasi di ScratchJr dengan merancang animasi bertema permainan bola basket yang dinamis dan seru.",
    "15": "Hari ini {nama} mulai merancang dan mengerjakan proyek akhir animasi kreatif di ScratchJr dengan memadukan seluruh konsep coding yang telah dipelajarinya.",
    "16": "Hari ini {nama} mengikuti sesi Review & Coding Challenge 2 (Lesson 9–15). {nama} menunjukkan pemahaman konsep animasi ScratchJr yang sangat baik dan percaya diri!",
    "17": "Hari ini {nama} mulai mengenal dunia game 3 Dimensi (3D Game) dan belajar membuat lingkungan game 3D pertamanya menggunakan aplikasi Kodu Game Lab.",
    "18": "Hari ini {nama} berlatih merancang dunia bawah laut (Underwater World) di Kodu 3D dengan menambahkan lanskap, air, dan karakter-karakter biota laut.",
    "19": "Hari ini {nama} belajar konsep logika *Conditional* (pengkondisian 'Jika... Maka...') dan memprogram sensor robot agar dapat merespons lingkungan sekitarnya.",
    "20": "Hari ini {nama} merancang game balapan sepeda 3D (Cycle Race) di Kodu Game Lab dengan mengatur lintasan, rintangan, dan kontrol pemain yang seru.",
    "21": "Hari ini {nama} membuat game tantangan 3D 'The Ground is Lava' di Kodu dengan melengkapi logika coding agar karakter melompat menghindari lava.",
    "22": "Hari ini {nama} berkenalan dengan sensor suara/tepukan tangan pada robot dan berhasil memprogram robot agar bergerak otomatis saat mendeteksi tepukan.",
    "23": "Hari ini {nama} menyusun rencana desain (design plan) dan mulai membuat proyek akhir 3D Game impiannya menggunakan Kodu Game Lab secara kreatif.",
    "24": "Hari ini {nama} mengikuti sesi Review & Coding Challenge 3 serta mempresentasikan hasil karya 3D Game buatannya. {nama} menunjukkan pencapaian yang membanggakan!"
  },

  "Adcanced Lua Programming on Roblox": {
    "1": "Hari ini {nama} mempelajari arsitektur game Battle Royale di Roblox Studio. {nama} mempersiapkan arena map, mengatur multiplayer game loop, dan membuat sistem chest interaktif yang dapat dibuka.",
    "2": "Hari ini {nama} merancang lobby system dan mengimplementasikan konsep *Table & For Loop (in pairs)* dalam bahasa Lua untuk membuat sistem teleportasi pemain otomatis ke arena.",
    "3": "Hari ini {nama} membuat model senjata (sword) 3D dan menyusun script Lua agar pemain dapat mengambil serta menggunakan senjata dari dalam chest.",
    "4": "Hari ini {nama} menambahkan item interaktif berupa potion penambah darah (health potion) serta mekanisme persenjataan player dalam game battle royale.",
    "5": "Hari ini {nama} menerapkan timer module dan merancang Screen GUI yang dinamis untuk menampilkan sisa waktu pertandingan dan status pemain secara real-time.",
    "6": "Hari ini {nama} memprogram logika akhir pertandingan (*ending match*) dan sistem pengembalian otomatis pemain yang tereliminasi kembali ke area lobby.",
    "7": "Hari ini {nama} menyusun skrip pembersihan map (*cleanup & map reset*) dan mekanisme transisi intermission antar babak permainan.",
    "8": "Hari ini {nama} mengikuti sesi Review & Mid Exam untuk menguji pemahaman scripting Lua dan mekanisme game Roblox. {nama} mampu menyelesaikan ujian dengan sangat baik!",
    "9": "Hari ini {nama} memulai proyek Cleaner Boat Simulator dengan merancang alur gameplay dan mempersiapkan aset material perahu serta sampah di perairan.",
    "10": "Hari ini {nama} merancang antarmuka Screen GUI khusus sistem perakitan perahu (*boat placement system*) agar pemain dapat memilih komponen dengan mudah.",
    "11": "Hari ini {nama} menyusun script Lua untuk logika *placement system*, memungkinkan pemain memasang dan memposisikan balok kapal secara interaktif.",
    "12": "Hari ini {nama} memprogram mekanisme peluncuran kapal (*launch boat*) ke air serta logika pembongkaran material kapal menggunakan coding.",
    "13": "Hari ini {nama} memprogram sistem pengumpulan sampah menggunakan kapal untuk mendapatkan koin, serta menampilkannya secara langsung di layar UI pemain.",
    "14": "Hari ini {nama} merancang kuis interaktif (Quiz GUI) sebagai syarat peningkatan kapasitas dan upgrade performa kapal.",
    "15": "Hari ini {nama} menyusun sistem manajemen kuis dan logika upgrade level kapal saat pemain berhasil menjawab tantangan dengan tepat.",
    "16": "Hari ini {nama} mengikuti sesi Review & Exam semester simulator Roblox. {nama} berhasil menunjukkan pemahaman logika pemrograman Lua yang solid!",
    "17": "Hari ini {nama} merancang game Math Obby (rintangan matematika) dengan memprogram sistem pembuatan soal acak secara otomatis menggunakan script Lua.",
    "18": "Hari ini {nama} memprogram pilihan jawaban pada platform obby dan membuat sistem validasi otomatis untuk mengecek jawaban pemain.",
    "19": "Hari ini {nama} mulai mengeksplorasi ide proyek game Roblox mandiri, menyusun lembar rencana (*game design document*), serta membangun model lingkungan 3D.",
    "20": "Hari ini {nama} melanjutkan tahap 3D modeling dan detailing untuk menyempurnakan tampilan visual dan arena map pada game Roblox buatannya.",
    "21": "Hari ini {nama} mulai menyusun script coding inti untuk mekanik gameplay, sistem interaksi, dan alur aturan permainan game Roblox mandirinya.",
    "22": "Hari ini {nama} melanjutkan penulisan kode Lua tingkat lanjut untuk menyempurnakan fitur-fitur khusus dan mengoptimalkan performa game.",
    "23": "Hari赋 {nama} belajar konsep monetisasi game dengan menambahkan fitur *Game Pass* dan item spesial di dalam game Roblox buatannya.",
    "24": "Hari ini {nama} mempresentasikan game Roblox hasil karyanya secara lengkap dan percaya diri kepada guru dan teman-teman. Kerja yang luar biasa!"
  },

  "AI Computer Vision": {
    "1": "Hari ini {nama} mempelajari konsep dasar *Computer Vision* dan manipulasi gambar menggunakan library OpenCV di Python, termasuk teknik *blurring* dan *filtering* gambar.",
    "2": "Hari ini {nama} mempelajari arsitektur Convolutional Neural Network (CNN) dan menggunakan framework TensorFlow untuk melatih model kecerdasan buatan berbasis citra.",
    "3": "Hari ini {nama} membuat proyek klasifikasi gambar (Horse vs Human) menggunakan dataset TensorFlow dan teknik augmentasi gambar (*Image Data Generator*).",
    "4": "Hari ini {nama} mengeksplorasi teknologi *Face Detection* menggunakan Pre-trained Model dan berhasil membuat aplikasi pendeteksi wajah pada gambar dan video real-time.",
    "5": "Hari ini {nama} mengimplementasikan arsitektur Single Shot Detector (MobileNet SSD) untuk mendeteksi berbagai objek secara akurat dan cepat dalam video stream.",
    "6": "Hari ini {nama} mempelajari perbedaan *Object Detection* dan *Object Tracking*, serta menerapkan teknik *Euclidean Distance Tracker* dan *contour detection* pada video.",
    "7": "Hari ini {nama} menyempurnakan sistem pelacakan objek dengan membuat class khusus untuk memberikan ID unik dan penanda visual pada setiap objek yang dilacak.",
    "8": "Hari ini {nama} mengikuti sesi Review Concepts & Middle Exam AI Computer Vision. {nama} berhasil membuktikan penguasaan teori dan praktik dengan sangat baik!",
    "9": "Hari ini {nama} membuat proyek Automatic Number Plate Recognition (ANPR) untuk membaca plat nomor kendaraan menggunakan Optical Character Recognition (EasyOCR).",
    "10": "Hari ini {nama} membuat sistem pengenalan tulisan tangan (*OCR Handwriting Recognition*) menggunakan kombinasi image processing dan model deep learning Keras.",
    "11": "Hari ini {nama} memanfaatkan library MediaPipe untuk mendeteksi titik koordinat tangan (*Hand Landmarks*) dan mulai merancang proyek interaktif *Virtual Painter*.",
    "12": "Hari ini {nama} menyelesaikan proyek *Virtual Painter*, di mana pengguna dapat memilih warna dan menggambar di udara menggunakan gerakan jari tangan melalui kamera.",
    "13": "Hari ini {nama} mengeksplorasi anatomi 468 titik Face Mesh di MediaPipe dan membuat filter wajah interaktif (Pig Face Filter) yang menempel presisi di wajah.",
    "14": "Hari ini {nama} mengembangkan class Face Mesh untuk mendeteksi area spesifik wajah (mata, hidung, mulut) serta membuat filter animasi bertema Dragon Filter.",
    "15": "Hari ini {nama} membuat sistem deteksi bukaan mulut dan kedipan mata untuk memicu efek animasi filter video yang dinamis saat ekspresi wajah berubah.",
    "16": "Hari ini {nama} mengikuti sesi Review & Final Exam AI Computer Vision. {nama} berhasil menyelesaikan seluruh tantangan coding dan evaluasi dengan hasil yang memuaskan!"
  },

  "AI Machine Learning": {
    "1": "Hari ini {nama} mempelajari konsep dasar Artificial Intelligence, Machine Learning, dan Deep Learning, serta berlatih mengolah dataset menggunakan library Pandas di Python.",
    "2": "Hari ini {nama} mempelajari algoritma klasifikasi, membagi dataset menjadi data latih (*train*) dan data uji (*test*), serta memvisualisasikan data Iris Flowers menggunakan Seaborn.",
    "3": "Hari ini {nama} melatih model klasifikasi menggunakan algoritma K-Nearest Neighbors (KNN), melakukan evaluasi akurasi, dan memprediksi spesies bunga baru secara otomatis.",
    "4": "Hari ini {nama} mengenal cabang Natural Language Processing (NLP) untuk pengolahan teks manusia dan mempraktikkan analisis teks menggunakan library NLTK dan ChatGPT API.",
    "5": "Hari ini {nama} mempelajari proses *feature extraction* dan *vectorization* teks, lalu membuat proyek analisis sentimen (*Sentiment Analysis*) ulasan pengguna Spotify.",
    "6": "Hari ini {nama} membandingkan performa algoritma klasifikasi Random Forest dan Naive Bayes untuk meningkatkan akurasi prediksi model analisis sentimen.",
    "7": "Hari ini {nama} membuat proyek pendeteksi berita palsu (*Fake News Detection*) menggunakan konsep NLP dan algoritma Logistic Regression.",
    "8": "Hari ini {nama} mengikuti sesi Review & Middle Exam Machine Learning. {nama} mampu memahami alur pemodelan data dan evaluasi model dengan sangat baik!",
    "9": "Hari ini {nama} mempelajari konsep *Time Series Forecasting* dan algoritma Linear Regression untuk membuat model prediksi pertumbuhan populasi.",
    "10": "Hari ini {nama} membuat proyek prediksi penjualan (*Sales Forecasting*), menerapkan teknik *feature engineering*, dan memvisualisasikan tren data menggunakan Plotly.",
    "11": "Hari ini {nama} mempelajari konsep dasar Jaringan Syaraf Tiruan (*Neural Network*) dan teknik transformasi data untuk membuat model prediksi yang lebih akurat.",
    "12": "Hari ini {nama} mempelajari metode *Unsupervised Learning* dan menerapkan algoritma K-Means Clustering untuk segmentasi kelompok pelanggan (*Customer Segmentation*).",
    "13": "Hari ini {nama} mempelajari cara kerja sistem rekomendasi (*Content-based* dan *Collaborative Filtering*) dan membangun sistem rekomendasi kursus otomatis.",
    "14": "Hari ini {nama} membangun model deteksi anomali (*Anomaly Detection*) menggunakan algoritma Isolation Forest untuk mendeteksi potensi transaksi mencurigakan pada kartu kredit.",
    "15": "Hari ini {nama} mengikuti sesi review materi komprehensif dan mengerjakan Ujian Tulis serta Ujian Praktik Coding Part 1.",
    "16": "Hari ini {nama} menyelesaikan Ujian Praktik Coding Part 2 dan mengumpulkan hasil proyek akhir Machine Learning dengan sukses. Hebat!"
  },

  "Android Developer": {
    "1": "Hari ini {nama} mulai mempelajari framework React Native dan komponen dasarnya (View, Text, Button) untuk merancang tampilan aplikasi mobile Android.",
    "2": "Hari ini {nama} mempelajari sistem styling layout (Box Model, Text Style) dan membuat tombol interaktif yang responsif menggunakan TouchableOpacity.",
    "3": "Hari ini {nama} mempelajari konsep Flexbox & Flex Direction untuk mengatur tata letak komponen, serta menambahkan gambar dan ScrollView pada aplikasi.",
    "4": "Hari ini {nama} mempelajari konsep *Props* untuk membuat komponen yang dapat digunakan kembali (*reusable components*), serta komponen ImageBackground & TextInput.",
    "5": "Hari ini {nama} belajar menambahkan custom font dan icon pack ke dalam aplikasi untuk mempercantik antarmuka layout populer yang modern.",
    "6": "Hari ini {nama} mempelajari React Hooks (`useState` dan `useEffect`) untuk mengelola state data dinamis pada proyek aplikasi 'Guess the Country Screen'.",
    "7": "Hari ini {nama} mengimplementasikan Stack Navigation untuk perpindahan antar layar aplikasi secara mulus dan memahami properti flexGrow.",
    "8": "Hari ini {nama} mengikuti sesi Review Concepts & Middle Test pembuatan aplikasi Android. {nama} berhasil menunjukkan pemahaman arsitektur aplikasi yang baik!",
    "9": "Hari ini {nama} mempelajari komponen FlatList dan StyleSheet di React Native untuk menampilkan daftar film pada proyek aplikasi 'Movie Collection'.",
    "10": "Hari ini {nama} mempelajari fitur FlatList horizontal dan teknik mengurutkan data (*sorting array of objects*) berdasarkan kriteria tertentu.",
    "11": "Hari ini {nama} mempelajari penggunaan Ternary Operator untuk tampilan kondisional dan menggabungkan StyleSheet dengan inline style pada aplikasi.",
    "12": "Hari ini {nama} memprogram sistem pengiriman dan penerimaan data antar layar aplikasi (*passing data between screens*) pada halaman Detail Movie.",
    "13": "Hari ini {nama} memprogram penanganan data kosong (*empty FlatList*), tata letak multi-kolom, dan merancang layar 'Most Viewed Movie'.",
    "14": "Hari ini {nama} mempelajari kustomisasi header pada Stack Navigation dan menyelesaikan perancangan layar 'Recommended Movie'.",
    "15": "Hari ini {nama} mengikuti Ujian Praktik Pembuatan Aplikasi Android Part 1 dengan mengimplementasikan komponen, styling, dan navigasi.",
    "16": "Hari ini {nama} menyelesaikan Ujian Praktik Pembuatan Aplikasi Android Part 2 dan berhasil menyusun aplikasi mobile fungsional secara mandiri. Keren!"
  },

  "Coding Explorer": {
    "1": "Hari ini {nama} mulai mengenal coding sebagai bahasa instruksi komputer dan belajar menyusun balok kode sesuai urutan algoritma yang benar dan logis.",
    "2": "Hari ini {nama} belajar konsep *Event* dan *Loop* dalam coding, serta berdiskusi tentang pentingnya mengatur waktu bermain gadget (*screen time*).",
    "3": "Hari ini {nama} membuat game interaktif sederhana di Scratch dan mempelajari literasi digital tentang cara mencegah serta bersikap bijak terhadap *cyber bullying*.",
    "4": "Hari ini {nama} mempelajari konsep logika *Conditional* (Jika... Maka...) dalam coding dan memahami cara merawat serta menjaga keamanan perangkat digital.",
    "5": "Hari ini {nama} mengeksplorasi teknologi Virtual Reality (VR) dan memahami pentingnya menjaga jejak digital (*digital footprints*) yang positif di internet.",
    "6": "Hari ini {nama} belajar konsep pengiriman pesan virtual dan memprogram simulasi pergerakan drone secara terarah.",
    "7": "Hari ini {nama} memahami arti *Bug* (kesalahan kode) dan cara memperbaikinya (*debugging*), serta memprogram animasi meluncur (*Glide*) pada game di Scratch.",
    "8": "Hari ini {nama} mengikuti sesi Review & Ujian *Exam Level Xplorer 1* (Meeting 1–7). {nama} berhasil menyelesaikan evaluasi pemahaman coding dengan sangat baik!",
    "9": "Hari ini {nama} belajar konsep *Conditional Loop* dan memprogram game seru 'Truth or Dare' menggunakan perangkat mikrokomputer Micro:bit.",
    "10": "Hari ini {nama} belajar algoritma pemecahan masalah dengan kode *Forever Loop*, serta berdiskusi tentang cara mengenali dan menghindari pesan spam di internet.",
    "11": "Hari ini {nama} belajar tentang keamanan komputer dari virus dan merancang akuarium 3D interaktif menggunakan Augmented Reality (AR Cube).",
    "12": "Hari ini {nama} merancang dan memprogram game terbang (*Flying Game*) di Scratch dengan kontrol karakter yang responsif dan menyenangkan.",
    "13": "Hari ini {nama} mempelajari konsep *Variable* untuk menyimpan nilai skor dalam game dan mengenal perkembangan teknologi dalam kehidupan sehari-hari.",
    "14": "Hari ini {nama} mempelajari konsep *Function* dalam coding untuk membuat instruksi yang efisien di lingkungan Virtual Reality (VR).",
    "15": "Hari ini {nama} mulai mengenal Artificial Intelligence (AI) dan berkenalan dengan bahasa pemrograman berbasis teks menggunakan Python.",
    "16": "Hari ini {nama} mengikuti sesi Review & Ujian *Exam Level Xplorer 2* (Meeting 9–15). {nama} menunjukkan pemahaman materi yang sangat memuaskan!",
    "17": "Hari ini {nama} mempelajari konsep *Broadcast Message* dan *Clone* (duplikasi karakter) di Scratch untuk membuat game interaktif yang lebih hidup.",
    "18": "Hari ini {nama} belajar tentang konsep Internet of Things (IoT) dan mempelajari struktur data *List* dalam coding untuk mengelola banyak data sekaligus.",
    "19": "Hari ini {nama} merancang dan memprogram game sepak bola interaktif (*Soccer Game*) di Scratch dengan logika pergerakan bola dan gawang.",
    "20": "Hari ini {nama} mempelajari konsep *Additive Design* dan mulai merancang lingkungan dunia game kreatif buatannya sendiri (*Create Own World - Part 1*).",
    "21": "Hari ini {nama} menentukan ide tema game mandirinya dan mulai mengumpulkan serta mendesain seluruh aset karakter dan latar permainan (*Part 1*).",
    "22": "Hari ini {nama} menyusun tata letak game, membuat layar pembuka (*Start Menu*), dan memprogram mekanisme utama permainan (*Part 2*).",
    "23": "Hari ini {nama} menambahkan sistem nyawa (*life*), papan skor (*score*), transisi ke level berikutnya, dan kondisi Game Over pada game buatannya (*Part 3*).",
    "24": "Hari ini {nama} menyelesaikan tahap *debugging*, mempresentasikan game hasil karyanya di hadapan kelas, dan saling berbagi feedback positif (*Part 4*).",
    "25": "Hari ini {nama} mulai mengenal pembuatan aplikasi mobile Android menggunakan platform visual MIT App Inventor.",
    "26": "Hari ini {nama} belajar logika *For Loop* dan waktu untuk membuat aplikasi 'Clicker App' dan aplikasi penghitung waktu ('Timer App').",
    "27": "Hari ini {nama} membuat aplikasi penerjemah bahasa (*Translator App*) dengan memanfaatkan komponen Spinner dan pengenal suara (*Speech Recognizer*).",
    "28": "Hari ini {nama} membuat aplikasi kalkulator pintar dan aplikasi 'My Walk App' yang dapat menghitung langkah kaki menggunakan sensor pedometer HP.",
    "29": "Hari ini {nama} membuat aplikasi papan gambar digital (*Drawing App*) serta merancang logika game klasik Tic-Tac-Toe.",
    "30": "Hari ini {nama} mengeksplorasi ide proyek aplikasi mobile mandiri, menyusun alur penggunaan, dan menyiapkan seluruh aset visual yang dibutuhkan.",
    "31": "Hari ini {nama} merancang tata letak antarmuka (UI Layout) dan menyusun blok coding untuk mengaktifkan fitur-fitur aplikasi mobile mandirinya.",
    "32": "Hari ini {nama} sukses meluncurkan (*launching*) dan mempresentasikan aplikasi mobile buatannya dengan sangat percaya diri dan membanggakan. Luar biasa!"
  },

  "Full Stack Programming on Roblox": {
    "1": "Hari ini {nama} mengenal antarmuka Roblox Studio, memahami proses 3D modeling, dan berhasil membuat game rintangan (Obby Game) pertamanya.",
    "2": "Hari ini {nama} mempelajari konsep fundamental coding di Roblox: *Variable*, *Properties*, dan teknik *reusing code* agar penulisan script lebih efisien.",
    "3": "Hari ini {nama} memperdalam teknik 3D modeling di Roblox Studio dan menambahkan efek-efek visual (*Particle & Lighting Effects*) pada objek game.",
    "4": "Hari ini {nama} merancang lanskap alam menggunakan Terrain Editor dan membuat platform penjualan barang (*sell platform*) pada game Mini Adventure.",
    "5": "Hari ini {nama} mempelajari cara membuat papan peringkat (*Leaderboard*) dan menerapkan konsep *Function* dalam script Lua untuk mengatur data pemain.",
    "6": "Hari ini {nama} memprogram objek yang dapat dipanen (*harvestable items*) menggunakan logika *Conditional Statement* (If-Else).",
    "7": "Hari ini {nama} memprogram mekanisme platform penjualan item untuk menghasilkan koin serta menambahkan rintangan dinamis di dalam map.",
    "8": "Hari ini {nama} mengikuti sesi Review & Exam evaluasi scripting Roblox. {nama} mampu menyelesaikan seluruh tantangan coding dengan sangat baik!",
    "9": "Hari ini {nama} belajar merancang karakter kustom (*Custom Player Character*) dan mengatur animasi serta pergerakannya di dalam game.",
    "10": "Hari ini {nama} mempelajari konsep *Event* di Roblox dan membuat model peluru 3D untuk mekanisme proyektil senjata.",
    "11": "Hari ini {nama} menyusun script Lua untuk memunculkan proyektil peluru (*spawn bullet*) dan mengatur arah serta kecepatan tembakannya.",
    "12": "Hari ini {nama} mempelajari konsep komunikasi client-server menggunakan *Remote Event* dan menghubungkannya dengan antarmuka Screen GUI dinamis.",
    "13": "Hari ini {nama} mempelajari konsep *ModuleScript* untuk merapikan struktur kode dan merancang sistem alur cerita (*story game*) pembuka.",
    "14": "Hari ini {nama} mempelajari pembuatan animasi karakter 3D di Roblox Animation Editor dan menerapkannya pada adegan cerita game.",
    "15": "Hari ini {nama} menerapkan komponen *ClickDetector* untuk interaksi objek serta menambahkan efek partikel khusus pada akhir cerita game.",
    "16": "Hari ini {nama} mengikuti sesi Review & Exam materi Roblox tingkat lanjut. {nama} menunjukkan penguasaan materi yang sangat memuaskan!",
    "17": "Hari ini {nama} mulai mengeksplorasi ide game mandiri, menyusun dokumen konsep game, dan membangun rancangan map 3D awal.",
    "18": "Hari ini {nama} melanjutkan tahap 3D modeling untuk menyelesaikan seluruh bangunan dan properti lingkungan pada game Roblox buatannya.",
    "19": "Hari ini {nama} mulai menyusun kode-kode script Lua utama untuk mengaktifkan sistem gameplay dan interaksi karakter.",
    "20": "Hari ini {nama} melanjutkan penulisan kode logika gameplay, sistem reward, dan mekanisme tantangan di dalam game.",
    "21": "Hari ini {nama} memprogram adegan penutup (*ending sequence*), layar kemenangan, dan merapikan seluruh fungsi script game.",
    "22": "Hari ini {nama} melakukan sesi playtest bersama teman sekelas, menerima masukan (feedback), dan melakukan perbaikan fitur (*bug fixing*).",
    "23": "Hari ini {nama} mempelajari konsep ekonomi digital di Roblox dan memprogram fitur *Game Pass* untuk monetisasi game buatannya.",
    "24": "Hari ini {nama} sukses mempresentasikan game Roblox hasil karyanya dan memainkannya bersama seluruh teman kelas. Proyek yang luar biasa!"
  },

  "Game Developer": {
    "1": "Hari ini {nama} mulai mengenal game engine Construct 3 dan belajar menggunakan *Behaviors* untuk menggerakkan karakter sprite pada platform melompat.",
    "2": "Hari ini {nama} menyusun labirin (*maze*) dan menggunakan *Event Sheet* untuk mengatur logika pergerakan dan interaksi karakter.",
    "3": "Hari ini {nama} mempelajari *Animation Frames* untuk membuat animasi karakter berjalan dan menambahkan perilaku *8 Direction* serta *Bound to Layout*.",
    "4": "Hari ini {nama} menambahkan karakter musuh (*enemy*), sistem penghitungan skor, dan mekanisme transisi ke level permainan berikutnya.",
    "5": "Hari ini {nama} memprogram sprite senjata agar membidik mengikuti posisi pointer mouse dan menerapkan *Physics Behavior* untuk simulasi gaya gravitasi.",
    "6": "Hari ini {nama} menambahkan efek partikel ledakan (*Particle Effect*) dan merancang tata letak rintangan baru pada Level 2 game.",
    "7": "Hari ini {nama} mengikuti sesi Review Materi (Meeting 1–6) untuk mematangkan konsep dasar pembuatan game 2D di Construct 3.",
    "8": "Hari ini {nama} mengikuti ujian *Exam Game Dev 1*. {nama} berhasil membuat game fungsional dengan mekanik yang lengkap dan rapi!",
    "9": "Hari ini {nama} membuat game pantulan bola (*Bouncing Ball*), memprogram pergerakan paddle, dan menggunakan *Instance Variables* pada balok rintangan.",
    "10": "Hari ini {nama} menambahkan sistem nyawa (*life*), mekanisme respawn bola saat jatuh, dan perancangan level tantangan baru.",
    "11": "Hari ini {nama} merancang tata letak antarmuka lengkap: Start Screen, Win Screen, dan Game Over Screen beserta tombol interaktif (*Start & Replay*).",
    "12": "Hari ini {nama} membuat efek latar bergerak (*scrolling background*), sistem pemilihan karakter, dan rintangan meteor jatuh acak.",
    "13": "Hari ini {nama} menampilkan indikator skor dan nyawa menggunakan *SpriteFont*, serta memanfaatkan fitur *Family* untuk mengelompokkan objek sejenis.",
    "14": "Hari ini {nama} menambahkan variasi musuh dengan *Instance Variables* unik dan mempercantik efek visual bintang menggunakan partikel *Stardust*.",
    "15": "Hari ini {nama} mengikuti sesi Review Materi (Meeting 9–14) dan mempersiapkan diri untuk evaluasi ujian game tingkat lanjut.",
    "16": "Hari ini {nama} mengikuti ujian *Exam Game Dev 2*. {nama} menunjukkan kreativitas dan pemahaman logika event sheet yang luar biasa!",
    "17": "Hari ini {nama} merancang tata letak level menggunakan *Tilemap* dan memprogram kontrol karakter platformer berbasis sentuhan (*Touch Controls*).",
    "18": "Hari ini {nama} menambahkan rintangan berbahaya, variasi musuh baru, serta item bonus koleksi yang dapat diambil oleh pemain.",
    "19": "Hari ini {nama} memprogram mekanisme menembak proyektil, membuat item menempel pada karakter, dan transisi mulus ke stage berikutnya.",
    "20": "Hari ini {nama} memprogram kecerdasan buatan sederhana pada musuh (*AI Enemy*) dan belajar cara mengekspor game untuk diunggah ke website.",
    "21": "Hari ini {nama} mulai merancang ide proyek game mandiri (*Game Creation - Part 1*) dan mengumpulkan seluruh aset gambar dan suara yang diperlukan.",
    "22": "Hari ini {nama} menyusun tata letak level, rintangan, dan mengatur struktur Event Sheet untuk game mandirinya (*Part 2*).",
    "23": "Hari ini {nama} melakukan tahap finishing, perbaikan bug (*debugging*), dan uji coba game sebelum peluncuran resmi (*Part 3*).",
    "24": "Hari ini {nama} resmi meluncurkan (*launching*) game buatannya dan mempresentasikannya dengan percaya diri di hadapan kelas. Hasil karya yang fantastis!"
  },

  "Code and Design with Roblox": {
    "1": "Hari ini {nama} mengenal perangkat komputer untuk game development, memahami etika literasi game, dan mulai mempersiapkan workspace di Roblox Studio.",
    "2": "Hari ini {nama} mempelajari menu dan tombol pintas (shortcuts) di Roblox Studio serta berhasil merancang dan membangun model rumah 3D pertamanya.",
    "3": "Hari ini {nama} belajar teknik meniru referensi gambar nyata menjadi model 3D, memahami fungsi *Anchor*, serta cara menyimpan dan berkolaborasi di Roblox.",
    "4": "Hari ini {nama} memahami hierarki objek (*Parent & Children*), memanfaatkan aset Toolbox secara bijak, dan menambahkan efek cahaya pada proyek rumah 3D.",
    "5": "Hari ini {nama} merancang lanskap lingkungan map menggunakan Terrain Editor dan memulai proyek baru dengan kontur alam yang indah.",
    "6": "Hari ini {nama} mempelajari penggunaan alat *Smooth* & *Flatten* pada Terrain Editor dan memanfaatkan plugin Brush Tool untuk mempercepat desain map.",
    "7": "Hari ini {nama} memahami aturan hak cipta aset digital (*Copyright*) dan berhasil mempublikasikan (*publish*) map hasil karyanya ke platform Roblox.",
    "8": "Hari ini {nama} mengikuti sesi Review & Exam Level 1. {nama} berhasil mendemonstrasikan penguasaan tools 3D modeling Roblox dengan sangat baik!",
    "9": "Hari ini {nama} mempelajari etika *Rings of Responsibility* di internet, menggunakan fitur *Generate Terrain*, dan membuat lingkungan game bawah air (Underwater).",
    "10": "Hari ini {nama} mempelajari teknik *Solid Modeling* (Union & Negate) untuk memotong objek 3D serta memahami hukum gravitasi objek di Roblox.",
    "11": "Hari ini {nama} mulai mempelajari dasar scripting Lua pada objek part dan memahami cara memodifikasi *Properties* objek melalui baris kode.",
    "12": "Hari ini {nama} menambahkan papan teks (*SurfaceGui TextLabel*), efek suara latar (*Sound*), dan mengatur pencahayaan atmosfer game.",
    "13": "Hari ini {nama} mempelajari konsep *Variable*, tipe data, fungsi `Instance.new()`, dan fungsi penundaan waktu `wait()` dalam coding Lua.",
    "14": "Hari ini {nama} mempelajari konsep perulangan *While Loop* dan menggunakannya untuk memprogram objek bergerak secara terus-menerus.",
    "15": "Hari ini {nama} mempelajari pembuatan animasi objek menggunakan tools animasi Roblox dan menerapkannya pada lingkungan bertema Farmland.",
    "16": "Hari ini {nama} mengikuti sesi Review & Exam Level 2 (Meeting 9–15). {nama} menunjukkan pemahaman modeling dan scripting yang sangat bagus!",
    "17": "Hari ini {nama} belajar menggunakan komponen *ImageLabel* pada objek part 3D untuk membuat papan nama dan label visual yang menarik.",
    "18": "Hari ini {nama} membuat sistem jebakan laser beranimasi (*Beam Effect*) pada pintu area terlarang menggunakan kombinasi part dan script.",
    "19": "Hari ini {nama} mulai mengeksplorasi ide proyek bangunan mandiri, membuat sketsa draft konsep, dan memulai tahap 3D modeling bangunan impiannya.",
    "20": "Hari ini {nama} mempelajari perpaduan kombinasi warna material dan melanjutkan tahap pembangunan detail struktur model 3D.",
    "21": "Hari ini {nama} menyelesaikan tahap akhir modeling 3D dengan menambahkan ornamen detail dan furnitur pada seluruh area bangunan.",
    "22": "Hari ini {nama} menambahkan objek-objek interaktif dan menyisipkan script coding agar model di dalam game dapat merespons aksi pemain.",
    "23": "Hari ini {nama} menyusun materi presentasi dan mempersiapkan poin-poin penting untuk menceritakan konsep karyanya.",
    "24": "Hari ini {nama} sukses mempresentasikan proyek 3D modeling dan game buatannya secara memukau di hadapan guru dan teman-teman. Selamat!"
  },

  "Interactive Mechanics on Roblox": {
    "1": "Hari ini {nama} merancang tata letak taman bermain (*Theme Park*), mengatur kontur tanah dengan Terrain Tools, dan mengkustomisasi atmosfer visual map.",
    "2": "Hari ini {nama} membuat model interaktif wahana komedi putar dan memprogram script Lua berbasis *Event* untuk menggerakkannya secara otomatis.",
    "3": "Hari ini {nama} belajar mendesain pakaian avatar menggunakan Photopea, mengimpor tekstur ke Asset Manager, dan memprogram kostum karakter di game.",
    "4": "Hari ini {nama} menyusun alur cerita game pelarian (*Escape Building Game*), merancang petunjuk tersembunyi (*clues*), dan membangun model gedungnya.",
    "5": "Hari ini {nama} membuat model kunci 3D dan menyusun script *Conditional Statement* (If-Else) untuk mekanisme membuka pintu yang terkunci.",
    "6": "Hari ini {nama} memprogram petunjuk teks (*clue text label*) interaktif dan menambahkan saklar lampu fungsional (*lightswitch*) pada ruangan game.",
    "7": "Hari ini {nama} mengonfigurasi pencahayaan senter kepala (*headlamp*), merapikan atmosfer suasana game, dan mempublikasikan game untuk dimainkan bersama.",
    "8": "Hari ini {nama} mengikuti sesi Review & Exam Meeting 1–7. {nama} berhasil menyelesaikan evaluasi mekanisme interaktif dengan nilai yang membanggakan!",
    "9": "Hari ini {nama} mulai mengenal software 3D Blender, mempelajari navigasi dasar dan kontrol shortcut, serta membuat model 3D pertamanya.",
    "10": "Hari ini {nama} membuat model botol dan aksesoris 3D di Blender, lalu mengekspor model tersebut ke dalam Roblox Studio.",
    "11": "Hari ini {nama} mengimpor objek 3D kustom, merancang tampilan antarmuka Screen GUI, dan menerapkan *TweenService* untuk animasi UI yang halus.",
    "12": "Hari ini {nama} merancang konsep game pencarian barang (*Finding Object Game*), membangun map dan gedung, serta menambahkan lukisan petunjuk.",
    "13": "Hari ini {nama} melanjutkan detail interior gedung, menentukan lokasi persembunyian objek, dan memprogram petunjuk Screen GUI untuk pemain.",
    "14": "Hari ini {nama} mendesain model 3D Low-Poly (tong/barrel) di Blender sebagai objek utama yang harus dicari dalam game pelarian.",
    "15": "Hari ini {nama} mengimpor aset Blender ke Roblox dan menyusun script sistem pengambilan objek (*collect system*) beserta notifikasi GUI-nya.",
    "16": "Hari ini {nama} mengikuti sesi Review & Exam Meeting 9–16. {nama} menunjukkan keterampilan memadukan 3D modeling Blender dan Roblox yang sangat baik!",
    "17": "Hari ini {nama} mempelajari struktur multi-tempat (*Places & Lobby System*), menghubungkan sub-game, serta membuat gambar badge prestasi dan game pass.",
    "18": "Hari ini {nama} mempelajari desain icon dan thumbnail game, membuat tombol kembali ke lobby (*return button*), dan merancang layar pembuka GUI.",
    "19": "Hari ini {nama} mulai merencanakan proyek game mandiri, membuat place baru di proyek lobby, dan memulai tahap 3D modeling di Blender dan Roblox.",
    "20": "Hari ini {nama} melanjutkan pemodelan 3D di Blender dan mengintegrasikan seluruh aset ke map Roblox dengan komposisi yang rapi.",
    "21": "Hari ini {nama} menambahkan antarmuka Screen GUI dan menyusun animasi transisi menggunakan *Tween Animation* agar tampilan game semakin profesional.",
    "22": "Hari ini {nama} memprogram alur misi utama dan menambahkan script teleportasi menggunakan event *Touch* saat pemain mencapai titik tertentu.",
    "23": "Hari ini {nama} merancang thumbnail promosi dan menyusun materi presentasi untuk menjelaskan alur dan keunikan game buatannya.",
    "24": "Hari ini {nama} mempresentasikan proyek game interaktif Roblox dan hasil 3D modeling Blender buatannya dengan sangat percaya diri. Luar biasa!"
  },

  "JavaScript Developer": {
    "1": "Hari ini {nama} mulai mengenal dunia pemrograman JavaScript, memahami bagaimana kode dieksekusi oleh komputer, dan belajar menyusun algoritma dasar yang runtut.",
    "2": "Hari ini {nama} mempelajari konsep *Variable* dan berbagai tipe data di JavaScript, serta berdiskusi kritis mengenai cara mengidentifikasi berita hoaks di internet.",
    "3": "Hari ini {nama} mempelajari macam-macam operator aritmatika, logika, dan operator penugasan (*assignment*) untuk memproses data angka dan teks dalam JavaScript.",
    "4": "Hari ini {nama} mempelajari struktur data *Array* untuk menyimpan banyak nilai dalam satu variabel, serta memahami etika positif dalam berkomunikasi di dunia digital.",
    "5": "Hari ini {nama} mempelajari logika percabangan *Conditional* (`if`, `else if`, `else`) menggunakan operator perbandingan dan logika untuk pengambilan keputusan program.",
    "6": "Hari ini {nama} mempelajari percabangan `switch-case` dan *Ternary Operator* untuk menulis kode pengkondisian yang lebih ringkas dan mudah dibaca.",
    "7": "Hari ini {nama} mempelajari konsep perulangan *For Loop* untuk menjalankan proses berulang secara otomatis dan memecahkan tantangan algoritma.",
    "8": "Hari ini {nama} mengikuti sesi Review Materi (Meeting 1–7) dan mengerjakan Middle Test JavaScript. {nama} menunjukkan pemahaman logika pemrograman yang sangat baik!",
    "9": "Hari ini {nama} mempelajari konsep perulangan bersarang (*Nested Loop*) dan *Conditional Loop* (`while`) untuk menangani pola data yang lebih kompleks.",
    "10": "Hari ini {nama} berlatih membuat beberapa program mini interaktif berbasis JavaScript untuk mengasah logika pemecahan masalah secara mandiri.",
    "11": "Hari ini {nama} mempelajari konsep *Function* (fungsi) untuk mengelompokkan baris kode agar rapi, modular, dan dapat digunakan kembali berkali-kali.",
    "12": "Hari ini {nama} memperdalam fungsi dengan menambahkan *Parameter* dan argumen dinamis sehingga fungsi dapat memproses berbagai input data yang fleksibel.",
    "13": "Hari ini {nama} mempelajari aturan ruang lingkup variabel (*Scope: Global & Local*) dalam JavaScript serta pentingnya menghormati hak cipta (*Copyright*) karya digital.",
    "14": "Hari ini {nama} mempelajari perintah *Return Statement* pada fungsi dan menggunakan metode iterasi modern `Array.forEach()` untuk mengolah data daftar.",
    "15": "Hari ini {nama} mengikuti sesi Review Komprehensif (Meeting 9–14) dan mempersiapkan diri menghadapi evaluasi ujian akhir JavaScript.",
    "16": "Hari ini {nama} mengikuti Ujian Akhir (*Final Exam*) JavaScript. {nama} berhasil menyelesaikan seluruh tantangan coding algoritma dengan sangat memuaskan!"
  },

  "Little Programmer": {
    "1": "Hari ini {nama} mengenal penyimpanan data digital (*Cloud Storage*) dan mengaplikasikan konsep *Variable* pada mikrokomputer Micro:bit untuk game 'Truth or Dare'.",
    "2": "Hari ini {nama} belajar tentang teknologi Internet of Things (IoT) yang membantu kehidupan sehari-hari dan mempelajari konsep struktur data *List* dalam coding.",
    "3": "Hari ini {nama} belajar konsep *Broadcast Message* di Scratch dan berhasil membuat proyek animasi kartu ucapan interaktif (*Greeting Card*).",
    "4": "Hari ini {nama} memahami konsep jejak digital (*Digital Footprints*) dan memprogram robot Maqueen menggunakan Micro:bit agar bergerak mengikuti garis (*Line Tracking*).",
    "5": "Hari ini {nama} belajar tentang interaksi komunitas digital dan merancang proyek animasi luar angkasa bertema 'Lost in Space' di Scratch.",
    "6": "Hari ini {nama} berlatih logika animasi dan membuat game terbang interaktif (*Flying Game*) di Scratch dengan kontrol yang responsif.",
    "7": "Hari ini {nama} belajar cara mengenali dan mencegah virus komputer, serta membuat game edukatif menggunakan konsep *List* di Scratch.",
    "8": "Hari ini {nama} mengikuti sesi Ujian Tulis & Coding Test 1. {nama} berhasil mendemonstrasikan pemahaman konsep coding dan robotika dengan sangat baik!",
    "9": "Hari ini {nama} mengingat kembali teknik Augmented Reality (AR) dan membuat kuis interaktif 3D di dalam dunia AR Delightex.",
    "10": "Hari ini {nama} mengenal konsep Sistem Operasi (OS) dan memprogram kontrol nirkabel (*Wireless Controller*) pada Micro:bit untuk mengemudikan robot Maqueen.",
    "11": "Hari ini {nama} belajar menggunakan fitur *Clone* (duplikasi otomatis) di Scratch untuk membuat animasi pertempuran klon (*Clone War Animation*).",
    "12": "Hari ini {nama} membuat museum virtual Augmented Reality yang menampilkan landmark dan bangunan bersejarah terkenal dari berbagai penjuru dunia.",
    "13": "Hari ini {nama} menyempurnakan proyek AR Landmark Dunia dengan menambahkan dialog dan coding interaktif pada setiap karakter pemandu.",
    "14": "Hari ini {nama} belajar memahami konsep desain adiktif (*Addictive Design*) dan mulai merancang game mandiri 'Create Your Own World - Part 1'.",
    "15": "Hari ini {nama} melanjutkan perancangan game 'Create Your Own World - Part 2' dengan melengkapi lanskap dan rintangan di dalam permainan.",
    "16": "Hari ini {nama} mengikuti sesi Ujian Tulis & Coding Test 2. {nama} menunjukkan kemajuan logika berpikir yang sangat pesat dan membanggakan!",
    "17": "Hari ini {nama} mulai mengenal konsep Kecerdasan Buatan (Artificial Intelligence) dan berkenalan dengan penulisan kode berbasis teks di Python.",
    "18": "Hari ini {nama} memanfaatkan internet sebagai sarana belajar mandiri dan memprogram robot menggunakan perpaduan operator matematika dan variabel.",
    "19": "Hari ini {nama} mulai merancang game sepak bola 2 pemain (*Soccer Game Part 1*) di Scratch dengan kontrol pergerakan pemain yang lincah.",
    "20": "Hari ini {nama} menyelesaikan game sepak bola di Scratch (*Soccer Game Part 2*), menambahkan efek gol, skor, dan memainkannya dengan gembira.",
    "21": "Hari ini {nama} menentukan ide kreatif untuk proyek game mandirinya dan mulai mengumpulkan serta menggambar seluruh aset karakter game.",
    "22": "Hari ini {nama} menyusun tata letak level, mendesain tampilan menu awal, dan menyusun blok coding mekanik utama game buatannya.",
    "23": "Hari ini {nama} melengkapi fitur game dengan menambahkan sistem nyawa, papan skor, efek suara, dan kondisi naik level (*Next Level*).",
    "24": "Hari ini {nama} resmi meluncurkan (*launching*) game hasil karyanya dan mempersiapkan presentasi untuk menunjukkan kehebatannya di depan kelas. Luar biasa!"
  },

  "Python Coder": {
    "1": "Hari ini {nama} mulai mempelajari dasar bahasa pemrograman Python, aturan sintaksnya, serta menggunakan perintah `print()` dan operator matematika untuk menghasilkan output program.",
    "2": "Hari ini {nama} mempelajari konsep *Variable*, fungsi input dari pengguna, tipe data dasar, struktur data *List*, dan menggambar pola visual menggunakan modul Python Turtle.",
    "3": "Hari ini {nama} mempelajari struktur data majemuk (List, Tuple, Dictionary, List 2D) dan memanfaatkan modul `random` untuk memilih data secara acak.",
    "4": "Hari ini {nama} mempelajari konsep perulangan *For Loop* dan *While Loop* dalam Python, serta memahami pentingnya aturan indentasi kode yang rapi dan benar.",
    "5": "Hari ini {nama} mempelajari logika percabangan `if-elif-else`, operator logika, penanganan *case-sensitive*, serta kombinasi perulangan berkondisi (*conditional loop*).",
    "6": "Hari ini {nama} mempelajari konsep pembuatan fungsi kustom (*def function*), perbedaan fungsi bawaan (*built-in*) dengan fungsi manual, dan pemanggilan fungsi.",
    "7": "Hari ini {nama} mempelajari teknik penulisan kode ringkas (*one-liner*) dan memanfaatkan parameter fungsi untuk membuat program yang fleksibel dan modular.",
    "8": "Hari ini {nama} mengikuti sesi Review & Middle Exam Python. {nama} berhasil menyelesaikan tantangan pemrograman dengan logika yang runtut dan rapi!",
    "9": "Hari ini {nama} mulai mengenal paradigma Object-Oriented Programming (OOP) dalam Python untuk memodelkan objek dunia nyata ke dalam baris kode.",
    "10": "Hari ini {nama} mengeksplorasi konsep dasar Artificial Intelligence (AI) dan mempraktikkan program sederhana berbasis kecerdasan buatan.",
    "11": "Hari ini {nama} mulai mempelajari modul Tkinter untuk merancang antarmuka grafis desktop (GUI) dengan berbagai komponen visual interaktif.",
    "12": "Hari ini {nama} menambahkan komponen antarmuka Tkinter tingkat lanjut seperti *MessageBox*, *InputBox*, *Label*, dan *Button* pada aplikasi GUI buatannya.",
    "13": "Hari ini {nama} mempelajari sistem koordinat kanvas grafis pada modul Tkinter untuk menggambar dan memposisikan objek secara presisi.",
    "14": "Hari ini {nama} mempelajari konsep penanganan peristiwa (*Event Handling*) untuk merespons klik mouse dan ketikan keyboard pada aplikasi desktop.",
    "15": "Hari ini {nama} mengikuti sesi Review Materi (Meeting 9–14) dan mempersiapkan diri menghadapi evaluasi proyek akhir Python.",
    "16": "Hari ini {nama} mengikuti Ujian Akhir (*Final Exam*) Python Coder. {nama} sukses menyelesaikan ujian dan menunjukkan pemahaman coding yang sangat matang. Hebat!"
  },

  "Python for AI": {
    "1": "Hari ini {nama} mempelajari konsep dasar Artificial Intelligence (AI), penerapannya dalam kehidupan modern, serta cara kerja algoritma Machine Learning.",
    "2": "Hari ini {nama} mendalami paradigma Object-Oriented Programming (OOP) di Python: memahami Class, Object, Method, Property, Inheritance, dan membuat game sederhana.",
    "3": "Hari ini {nama} mempelajari library NumPy untuk komputasi array multidimensi (1D, 2D, 3D), operasi matriks, dan membuat proyek logika Tic-Tac-Toe dengan NumPy.",
    "4": "Hari ini {nama} mulai mempelajari Computer Vision dengan library OpenCV, memproses citra digital, manipulasi warna piksel, dan teknik *image blurring*.",
    "5": "Hari ini {nama} mempelajari teknik deteksi tepi (*Canny Edge Detector*), deteksi kontur, segmentasi warna di OpenCV, dan membuat proyek 'Image Cartoonizer'.",
    "6": "Hari ini {nama} memanfaatkan Pre-trained Machine Learning Model untuk membangun aplikasi pendeteksi wajah (*Face Detection*) pada gambar dan video real-time.",
    "7": "Hari ini {nama} mengimplementasikan arsitektur Single Shot MultiBox Detector (MobileNet SSD) untuk mendeteksi berbagai jenis objek secara akurat.",
    "8": "Hari ini {nama} mengikuti sesi Review & Middle Exam Python for AI. {nama} berhasil membuktikan penguasaan konsep teori dan implementasi kode dengan luar biasa!",
    "9": "Hari ini {nama} mempelajari konsep *Object Tracking*, perbedaan deteksi vs pelacakan objek, serta algoritma pelacakan jarak Euclidean Distance.",
    "10": "Hari ini {nama} mengembangkan class pelacak objek kustom (*Euclidean Distance Tracker*) dengan penomoran ID unik dan penanda visual pada target yang dilacak.",
    "11": "Hari ini {nama} memanfaatkan library MediaPipe untuk mendeteksi 21 titik sendi tangan (*Hand Landmarks*) dan merancang proyek kanvas virtual (*Virtual Painter*).",
    "12": "Hari ini {nama} menyempurnakan proyek *Virtual Painter* dengan menambahkan mode pemilihan kuas, palet warna, dan menggambar di udara menggunakan jari.",
    "13": "Hari ini {nama} mempelajari model MediaPipe Face Mesh (468 titik landmark wajah) dan membuat filter interaktif 3D (Pig Face Filter).",
    "14": "Hari ini {nama} membuat class Face Mesh kustom untuk mendeteksi area spesifik wajah dan mengaplikasikan efek animasi 'Dragon Filter' pada video kamera.",
    "15": "Hari ini {nama} membuat algoritma deteksi ekspresi bukaan mulut dan kedipan mata untuk memicu efek animasi filter video secara otomatis.",
    "16": "Hari ini {nama} mengikuti sesi Summary & Final Exam Python for AI. {nama} berhasil menuntaskan seluruh proyek dan ujian akhir dengan pencapaian yang membanggakan!"
  },

  "Python for Data Science": {
    "1": "Hari ini {nama} mempelajari pengantar Data Science, setup lingkungan kerja Python, sintaks dasar, variabel, tipe data, operator, dan penanganan input data.",
    "2": "Hari ini {nama} mendalami struktur data Python (List 1D/2D, Tuples) beserta metode manipulasi data, lalu membuat proyek 'Password Generator'.",
    "3": "Hari ini {nama} mempelajari konsep Dictionary untuk mengelola data berpasangan (*Key-Value*), menggabungkan struktur data, dan membuat proyek 'Movie Dictionary'.",
    "4": "Hari ini {nama} mempelajari teknik perulangan (*For & While Loops*), teknik *list comprehension* satu baris, dan latihan optimasi pengulangan data.",
    "5": "Hari ini {nama} mempelajari logika percabangan bersarang (*Nested Conditions*), menggabungkannya dengan perulangan, dan membuat proyek permainan kata 'Jumbled Word'.",
    "6": "Hari ini {nama} mempelajari pembuatan fungsi kustom (*def function*), aturan scope variabel, dan merancang bot interaktif menggunakan Discord.py.",
    "7": "Hari ini {nama} mempelajari konsep Object-Oriented Programming (OOP) dalam Python: membedakan Object, Class, Method, Inheritance, dan membuat game berbasis OOP.",
    "8": "Hari ini {nama} mengikuti sesi Review & Middle Exam Data Science. {nama} menunjukkan pemahaman dasar pengolahan data Python yang sangat solid!",
    "9": "Hari ini {nama} mempelajari algoritma pengurutan data (Bubble Sort, Insertion Sort) dan algoritma pencarian data (Linear Search) dalam Python.",
    "10": "Hari ini {nama} mempelajari library komputasi ilmiah NumPy, manipulasi array multidimensi, dan mengaplikasikannya pada proyek permainan Tic-Tac-Toe.",
    "11": "Hari ini {nama} mulai menggunakan Google Colab dan library Pandas untuk mengimpor, membersihkan, dan memanipulasi dataset tabular (DataFrame).",
    "12": "Hari ini {nama} mempelajari alur analisis data bisnis, melakukan penilaian kualitas data (*data assessment*), dan membersihkan data (*data cleaning*) pada dataset E-Commerce.",
    "13": "Hari ini {nama} melakukan Exploratory Data Analysis (EDA), pengelompokan data (*grouping*), dan membuat grafik visualisasi data yang informatif untuk menjawab pertanyaan bisnis.",
    "14": "Hari ini {nama} mempelajari hubungan teori probabilitas dengan Artificial Intelligence, distribusi data statistik, dan simulasi probabilitas melempar koin/dadu.",
    "15": "Hari ini {nama} mengikuti sesi Review Materi Komprehensif (Meeting 9–14) dan mempersiapkan diri menghadapi evaluasi akhir.",
    "16": "Hari ini {nama} mengikuti Ujian Akhir (*Final Exam*) Python for Data Science. {nama} berhasil menyelesaikan analisis data dan studi kasus dengan sangat memuaskan!"
  },

  "Python Game Developer": {
    "1": "Hari ini {nama} mulai mempelajari library Pygame di Python, mempersiapkan jendela game, memahami game loop, event controller, dan menambahkan objek visual pertama.",
    "2": "Hari ini {nama} mengatur frame rate (FPS) game, memprogram pergerakan objek pada kanvas Pygame, membuat transisi layout, dan menampilkan teks skor.",
    "3": "Hari ini {nama} mempelajari gaya pemrograman modular menggunakan fungsi, manajemen folder aset game, serta teknik memuat (*load*) gambar sprite dan sound effects.",
    "4": "Hari ini {nama} mengimplementasikan konsep fisika gravitasi, menghitung kecepatan (*velocity*) dan percepatan (*acceleration*), serta menghapus objek yang keluar dari layar.",
    "5": "Hari ini {nama} memprogram sistem deteksi tabrakan (*Collision Detection*) antar sprite, mengelola variabel skor global, dan menyimpan nilai *High Score*.",
    "6": "Hari ini {nama} mempelajari konsep game multiplayer lokal dan menerapkan fungsi transformasi gambar (rotasi dan penskalaan sprite) di Pygame.",
    "7": "Hari ini {nama} mendalami class `pygame.Rect()`, merespons input keyboard terus-menerus (`get_pressed()`), dan merapikan kode game menjadi fungsi-fungsi modular.",
    "8": "Hari ini {nama} memprogram custom event di Pygame, merancang layar kemenangan (*Winning Screen*), dan belajar mengonversi game Python menjadi file *executable* (.exe).",
    "9": "Hari ini {nama} mempelajari teknik animasi sprite multi-frame di Pygame, menambahkan custom font eksternal, dan mengelola pewaktuan menggunakan modul time.",
    "10": "Hari ini {nama} menyempurnakan simulasi gravitasi, memprogram pemunculan musuh secara berkala (*enemy spawning*), dan menambahkan musik latar (*BGM*).",
    "11": "Hari ini {nama} mulai merancang proyek game mandiri, menyusun alur cerita dan aturan game, mengumpulkan aset grafis, dan menyiapkan struktur foldernya.",
    "12": "Hari ini {nama} melanjutkan pembuatan game mandiri dengan mendesain tata letak antarmuka setiap layar dan menyusun susunan sprite pemain.",
    "13": "Hari ini {nama} memprogram logika kontrol karakter utama, mekanik aksi, dan sistem pergerakan animasi karakter pada game mandirinya.",
    "14": "Hari ini {nama} menambahkan perilaku musuh (*enemy AI logic*), rintangan bertahap, dan sistem penghitungan skor pada proyek game buatannya.",
    "15": "Hari ini {nama} memprogram kondisi Game Over dan Game Win, melakukan tahap uji coba (*playtest*), serta memperbaiki kendala teknis (*bug fixing*).",
    "16": "Hari ini {nama} sukses mengompilasi game Python buatannya menjadi aplikasi mandiri (.exe) dan mempresentasikannya dengan bangga di hadapan kelas. Luar biasa!"
  },

  "Virtual World Maker": {
    "1": "Hari ini {nama} mengingat kembali konsep dasar coding sebagai instruksi komputer dan berlatih menyusun blok kode sesuai algoritma yang teratur dan logis.",
    "2": "Hari ini {nama} belajar konsep *Event* dalam coding serta berdiskusi mengenai pentingnya menjaga keseimbangan waktu penggunaan gadget (*screen time*).",
    "3": "Hari ini {nama} mempelajari konsep *Loop* (perulangan) dalam coding dan memahami pentingnya etika digital untuk mencegah perilaku *cyber bullying*.",
    "4": "Hari ini {nama} berlatih membuat animasi interaktif di Scratch dan mengeksplorasi berbagai fitur kreatif yang tersedia.",
    "5": "Hari ini {nama} mempelajari konsep logika *Conditional* (pengkondisian 'Jika... Maka...') dan memprogram pergerakan karakter menggunakan blok kode 'If'.",
    "6": "Hari ini {nama} berdiskusi tentang pentingnya *Media Balance* (gaya hidup digital seimbang) dan memprogram gerakan robot pada platform baru.",
    "7": "Hari ini {nama} memahami perbedaan komunikasi langsung dengan komunikasi online, serta belajar mengendalikan simulasi drone secara virtual.",
    "8": "Hari ini {nama} mengikuti sesi Review & Evaluasi Capaian (Meeting 1–7). {nama} berhasil menunjukkan pemahaman konsep coding dan literasi digital yang sangat baik!",
    "9": "Hari ini {nama} memahami arti *Bug* pada program dan berhasil membuat game 'Bug Hunter' menggunakan konsep logika *Conditional*.",
    "10": "Hari ini {nama} belajar menggunakan perintah 'Glide' untuk membuat gerakan sprite yang halus dan merancang game balapan 'Beetle Race' di Scratch.",
    "11": "Hari ini {nama} memahami pentingnya menghargai hak cipta (*Copyright*) karya orang lain dan mengaplikasikan konsep *Function* pada game buatannya.",
    "12": "Hari ini {nama} mengingat kembali manfaat konsep *Function* dalam coding dan mengimplementasikannya untuk memprogram serangkaian gerakan robot.",
    "13": "Hari ini {nama} belajar tentang nilai pantang menyerah saat menghadapi tantangan coding dan mempelajari konsep *Conditional Loop*.",
    "14": "Hari ini {nama} belajar cara mengenali dan menghindari pesan spam di internet serta menggunakan balok kode *Forever Loop* dalam membuat animasi.",
    "15": "Hari ini {nama} mulai mengenal mikrokomputer Micro:bit dan belajar memprogram lampu LED Micro:bit menggunakan instruksi perulangan *Forever*.",
    "16": "Hari ini {nama} mengikuti sesi Review & Evaluasi Capaian (Meeting 9–15). {nama} menunjukkan pemahaman materi dan antusiasme belajar yang tinggi!",
    "17": "Hari ini {nama} mengeksplorasi teknologi Virtual Reality (VR) dan berhasil merancang pameran kebun binatang virtual (*Animal VR Exhibition*) di Delightex.",
    "18": "Hari ini {nama} mengaplikasikan konsep *Function* di lingkungan VR Delightex untuk membuat game eksplorasi interaktif 'Finding Animal'.",
    "19": "Hari ini {nama} berdiskusi tentang kemajuan teknologi dalam kehidupan sehari-hari dan mempelajari konsep *Variable* untuk menyimpan data dalam game.",
    "20": "Hari ini {nama} merancang tur kota virtual 3D ('VR City Tour') di Delightex dengan pemandangan jalan raya dan gedung-gedung interaktif.",
    "21": "Hari ini {nama} mempelajari konsep *Operator* matematika dalam coding dan mengaplikasikannya untuk membuat game kuis berhitung (*Math Game*).",
    "22": "Hari ini {nama} berdiskusi tentang cara mengidentifikasi berita hoaks di internet dan mulai membuat diorama multi-adegan di dunia Virtual Reality.",
    "23": "Hari ini {nama} menyempurnakan proyek diorama tata surya 3D (*Solar System VR*) dan mempresentasikannya dengan sangat menarik dan edukatif.",
    "24": "Hari ini {nama} mengikuti sesi Review Komprehensif & Ujian Akhir (Meeting 17–23). {nama} berhasil menyelesaikan evaluasi dan proyek akhir dengan sangat membanggakan!"
  },

  "Web Developer Teens": {
    "1": "Hari ini {nama} mulai mengenal cara kerja website dan mempelajari struktur dasar HTML: tag heading, paragraf, baris baru, serta format teks (tebal, miring, garis bawah).",
    "2": "Hari ini {nama} mempelajari bahasa penata tampilan CSS (Cascading Style Sheets), memahami konsep CSS Box Model, selector, dan merancang bagian header website yang rapi.",
    "3": "Hari ini {nama} mempelajari teknik tata letak modern *Flexbox* (display: flex) untuk menyusun kartu produk (*Product Cards*) dan galeri gambar yang rapi.",
    "4": "Hari ini {nama} mempelajari pembuatan struktur tabel HTML beserta atribut penggabungan baris dan kolom (*Rowspan & Colspan*) pada halaman website.",
    "5": "Hari ini {nama} mempelajari format daftar (*List*) dan pembuatan tombol interaktif di HTML, lalu merancang tabel daftar harga (*Pricing Table*).",
    "6": "Hari ini {nama} mempelajari konsep tautan (*Hyperlink & Anchor Link*), perbedaan URL absolut vs relatif, dan menambahkan halaman 'About Us'.",
    "7": "Hari ini {nama} mengintegrasikan icon modern dari Font Awesome dan merancang bagian footer website dengan gradasi warna yang menarik.",
    "8": "Hari ini {nama} menerapkan Google Fonts kustom, memahami prinsip desain website responsif, dan belajar cara mengunggah situs web ke internet.",
    "9": "Hari ini {nama} mulai mempelajari integrasi JavaScript dalam dokumen HTML, memahami DOM (Document Object Model), dan membuat halaman blog interaktif.",
    "10": "Hari ini {nama} mempelajari konsep event pada DOM (klik tombol, input) untuk membuat interaksi dinamis pada proyek website blog.",
    "11": "Hari ini {nama} menambahkan elemen multimedia video dan audio HTML5 serta menyematkan (*embed*) konten media eksternal ke dalam website.",
    "12": "Hari ini {nama} mempelajari pembuatan formulir HTML (*HTML Form*) lengkap dengan elemen input, label, textarea, select, dan atribut formulir.",
    "13": "Hari ini {nama} memperdalam jenis-jenis tag input formulir (email, password, radio, checkbox) dan validasi data masukan dari pengguna.",
    "14": "Hari ini {nama} memberikan styling CSS modern pada formulir dan menghubungkan pengiriman data formulir langsung ke layanan email.",
    "15": "Hari ini {nama} memprogram jendela pop-up interaktif (*Modal Popup*) menggunakan kombinasi HTML, CSS, dan JavaScript pada website.",
    "16": "Hari ini {nama} membuat slider gambar manual dan otomatis (*Autoplay Image Slider*) menggunakan metode iterasi `forEach` di JavaScript.",
    "17": "Hari ini {nama} mengeksplorasi pembuatan ornamen visual modern (Blob shapes, gelombang/waves, latar belakang gradien dinamis) pada website.",
    "18": "Hari ini {nama} mempelajari efek transisi dan animasi CSS (*keyframes*) serta mengimplementasikan efek kemunculan konten saat di-scroll (*Reveal on Scroll*).",
    "19": "Hari ini {nama} mengoptimalkan tata letak website agar tampil sempurna dan responsif di berbagai ukuran layar (smartphone, tablet, desktop).",
    "20": "Hari ini {nama} mulai merencanakan proyek website mandiri: memilih tema, menyusun peta situs (*sitemap*), dan membuat wireframe desain antarmuka.",
    "21": "Hari ini {nama} mempersiapkan struktur file proyek dan mulai membangun halaman utama (*Home Page*) lengkap dengan navigasi dan hero section.",
    "22": "Hari ini {nama} menyelesaikan perancangan halaman detail layanan/produk serta halaman profil 'About Us' dengan konten yang lengkap.",
    "23": "Hari赋 {nama} merancang halaman 'Contact Us' yang responsif dan menyempurnakan seluruh tautan navigasi antar halaman website.",
    "24": "Hari ini {nama} berhasil mempublikasikan (*deploy*) website hasil karyanya secara live ke Netlify dan mempresentasikannya dengan sangat percaya diri. Kerja luar biasa!"
  },

  "Website Designer": {
    "1": "Hari ini {nama} belajar konsep *Conditional Loop* dalam coding dan memprogram pergerakan robot secara otomatis menggunakan instruksi perulangan berkondisi.",
    "2": "Hari ini {nama} mengenal teknologi Virtual Reality (VR) dan mulai belajar merancang lingkungan dunia 3D pertamanya menggunakan platform Delightex.",
    "3": "Hari ini {nama} berlatih merancang kota virtual 3D (*My Virtual City*) di Delightex dengan menambahkan jalan, pepohonan, mobil, dan gedung-gedung megah.",
    "4": "Hari ini {nama} mempelajari konsep *Function* dalam coding dan mengaplikasikannya untuk mengelompokkan serangkaian instruksi pergerakan robot.",
    "5": "Hari ini {nama} mengenal teknologi Augmented Reality (AR) dan belajar merancang objek serta animasi 3D interaktif di Delightex.",
    "6": "Hari ini {nama} merancang dan mendekorasi rumah virtual 3D di Delightex lengkap dengan ruangan, furnitur, dan efek pencahayaan.",
    "7": "Hari ini {nama} mulai merancang dan mengerjakan proyek akhir dunia Virtual Reality impiannya menggunakan seluruh fitur kreatif di Delightex.",
    "8": "Hari ini {nama} mengikuti sesi Review & Coding Challenge 1. {nama} berhasil menunjukkan pemahaman konsep desain VR/AR dan logika coding dengan sangat baik!",
    "9": "Hari ini {nama} berlatih merancang proyek Augmented Reality bertema akuarium bawah laut interaktif lengkap dengan animasi ikan berenang di Delightex.",
    "10": "Hari ini {nama} memulai proyek akhir AR bertema 'All About Me' dengan menyusun biodata, hobi, dan karakter 3D favoritnya secara interaktif.",
    "11": "Hari ini {nama} menyelesaikan seluruh detail proyek akhir AR 'All About Me' dan menyempurnakan interaksi coding pada setiap elemen 3D.",
    "12": "Hari ini {nama} mulai mengenal dunia web dan belajar membuat halaman website sederhana pertama dengan menyusun struktur teks dan gambar.",
    "13": "Hari ini {nama} mulai merancang proyek akhir website pribadi, menata tata letak biodata, foto, dan etalase karya proyek yang telah dibuatnya.",
    "14": "Hari ini {nama} menambahkan halaman-halaman pendukung ke dalam website dan menghubungkannya dengan tombol navigasi yang rapi.",
    "15": "Hari ini {nama} mempercantik tampilan website dengan tombol-tombol interaktif, warna menarik, dan menyempurnakan penataan konten.",
    "16": "Hari ini {nama} resmi menyelesaikan dan mempublikasikan website hasil karyanya ke internet serta mempresentasikannya dengan bangga. Selamat!"
  }
};

// Verify completeness against scratch_course_data.json
const cd = JSON.parse(fs.readFileSync('scratch_course_data.json', 'utf8'));
let missing = 0;
for (let c in cd) {
  if (!TEMPLATES[c]) {
    console.error('MISSING COURSE:', c);
    missing++;
  } else {
    for (let l of cd[c]) {
      if (!TEMPLATES[c][String(l.num)]) {
        console.error(`MISSING LESSON in ${c}: Lesson ${l.num}`);
        missing++;
      }
    }
  }
}

if (missing === 0) {
  console.log('All 19 courses and 392 lessons are 100% matched and verified!');
  fs.writeFileSync('scratch_templates.json', JSON.stringify(TEMPLATES));
} else {
  console.error('Total missing:', missing);
}
